### ISSUE TITLE
tell the author that /tools/prepare.sh fails on your system - node Error - Ubuntu 16.04.3 

### ISSUE THREAD

**Issue by randomly123** [balena-io/docs#679] opened 2018-01-10 04:54 UTC
/resin-docs/tools$ ./prepare.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142  100   142    0     0     83      0  0:00:01  0:00:01 --:--:--    83
100 35873  100 35873    0     0   9789      0  0:00:03  0:00:03 --:--:-- 27425
/home/rw2/resin-docs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   144  100   144    0     0     95      0  0:00:01  0:00:01 --:--:--    95
100  2449  100  2449    0     0    812      0  0:00:03  0:00:03 --:--:--  1896
/home/rw2/resin-docs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142  100   142    0     0     86      0  0:00:01  0:00:01 --:--:--    86
100  143k  100  143k    0     0  35407      0  0:00:04  0:00:04 --:--:--  113k
/home/rw2/resin-docs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   149  100   149    0     0     97      0  0:00:01  0:00:01 --:--:--    97
100 56712  100 56712    0     0  15530      0  0:00:03  0:00:03 --:--:-- 63224
/home/rw2/resin-docs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   144  100   144    0     0     82      0  0:00:01  0:00:01 --:--:--    82
100 15493  100 15493    0     0   4215      0  0:00:03  0:00:03 --:--:-- 25440
/home/rw2/resin-docs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   155  100   155    0     0     20      0  0:00:07  0:00:07 --:--:--    38
100  4315  100  4315    0     0    474      0  0:00:09  0:00:09 --:--:--  4695
/home/rw2/resin-docs

> resin-docs@1.1.4 build /home/rw2/resin-docs
> ./tools/build.sh && webpack -p

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.10.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! resin-docs@1.1.4 build: `./tools/build.sh && webpack -p`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the resin-docs@1.1.4 build script './tools/build.sh && webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the resin-docs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./tools/build.sh && webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs resin-docs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls resin-docs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rw2/resin-docs/npm-debug.log

resin-docs/tools$ **sudo apt-get install node.js**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'node-jsv' for regex 'node.js'
Note, selecting 'node-jsdom' for regex 'node.js'
Note, selecting 'node-jsesc' for regex 'node.js'
Note, selecting 'node-json-stringify-safe' for regex 'node.js'
Note, selecting 'node-jscoverage' for regex 'node.js'
Note, selecting 'node-jssip' for regex 'node.js'
Note, selecting 'node-jsonparse' for regex 'node.js'
node-jsdom is already the newest version (0.8.10+dfsg1-1).
node-jsesc is already the newest version (0.5.0-1).
node-json-stringify-safe is already the newest version (5.0.0-1).
node-jsonparse is already the newest version (1.0.0-1).
node-jssip is already the newest version (0.6.34-5).
node-jsv is already the newest version (4.0.0+ds1-1).
**0 upgraded, 0 newly installed, 0 to remove and 162 not upgraded.**
rw2@rw2-ThinkPad-T530:~/resin-docs/tools$ **sudo apt-get install npm**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
npm is already the newest version (3.5.2-0ubuntu4).
**0 upgraded, 0 newly installed, 0 to remove and 162 not upgraded.**

**Comment by sradevski** [comment] 2019-03-22 18:27
I couldn't reproduce the issue. I believe this is not a problem with prepare.sh, but with node either incorrectly installed or having an older version of it. Closing.

**Closed by sradevski** 2019-03-22 18:27 UTC
Labels: docs/meta, status/needs investigation
