### ISSUE TITLE
404 page on docs renders without any styling

### ISSUE THREAD

**Issue by cyplo** [balena-io/docs#940] opened 2018-11-09 08:21 UTC
NUC flashing instructions `dashboard->application->add device` link to getting started guide using this URL:
http://docs.resin.io/nuc/nodejs/getting-started/#adding-your-first-device , this gets redirected to
https://www.balena.io/docs/learn/getting-started/docs/intel-nuc/nodejs/#adding-your-first-device

The page loads as pure text, with no styles in both Firefox and Chromium under Linux

![screenshot from 2018-11-09 08-18-11](https://user-images.githubusercontent.com/217899/48251109-75a5e100-e3f8-11e8-86b9-e4cb2f91aba5.png)

**Comment by lurch** [comment] 2018-11-10 00:57
If you scroll all the way to the bottom you can see it says
```
Page not found
We think we don't have a page you're looking for.
```

**Comment by chrisys** [comment] 2018-11-15 22:17
@cyplo this appears to be fixed now, or at least I cannot reproduce it. Reopen if still an issue 👍

**Comment by lurch** [comment] 2018-11-16 17:32
@chrisys Looks like any non-existent page still displays as completely unstyled, e.g. https://www.balena.io/docs/learn/page-not-here

**Comment by chrisys** [comment] 2018-11-16 17:36
@lurch thanks for pointing that out, have reopened and renamed to keep all the discussion here.

**Comment by sradevski** [comment] 2019-03-13 21:32
I just had a quick look at it, and the issue seems to be that the not-found page looks for the style and js at `/dist/<styles.css|main.js>`, but the other pages fetch it from `/docs/dist/<styles.css|main.js>`. I am assuming the reason is doxx adds the prefix to all static pages, but the not-found pages is not handled by doxx, therefore the error.

**Closed** 2019-03-25 10:37 UTC
Labels: in progress
