### ISSUE TITLE
Create some info on Power Supplies

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#149] opened 2016-01-21 14:23 UTC
Make a small page with recommended PSUs and the case that poor supplies will at times cause SD card corruption, etc

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_13ia)

**Comment by vipulgupta2048** [comment] 2020-12-28 11:51
@ntzovanis Maybe you can help here me here? Would it be relevant to have this information now.

**Comment by ntzovanis** [comment] 2020-12-28 14:23
@vipulgupta2048 sure, what's the context on this? PSUs for what type of board? What is it that we're trying to achieve here?

**Comment by lurch** [comment] 2020-12-28 15:23
I _suspect_ the original context here was people using "cheap" micro-USB PSUs (e.g. a generic phone charger) to power e.g. a Raspberry Pi. If the PSU is insufficient and the Pi starts doing something CPU-intensive (or controls something with its GPIO pins), then the Pi may draw more current than the PSU can supply, which will cause the Pi to brown-out; and like any unexpected-reset-event this can cause the filesystem on the SD card to become corrupt (which in the worst-case-scenario might cause the Pi to fail to boot until the SD card is re-flashed).

**Comment by vipulgupta2048** [comment] 2020-12-28 19:55
Hey @ntzovanis I have taken up some Docs Cleanup this time round. I don't have a lot of context for you apart from the front conversation linked in the first message by Shaun (4 years old). Reading from the messages there, it seems like the issue was diagnosed as SD card corruption due to heavy read/writes. Another leading cause for that might be an inefficient PSU that they might be using as lurch suggested above. Hence, was my question if we could have any relevant information of PSU that folks could use according to their board type which I agree is a very broad, not to mention vague question. 

What we can do?
- How about a small FAQ answer on the [FAQ page](https://www.balena.io/docs/faq/troubleshooting/faq/) about better reading voltage requirements to pick the right PSU for the board that customers might be using?
- Any useful advice other than what's already mentioned here under power - https://www.balena.io/docs/learn/welcome/production-plan/#hardware

If nothing comes to mind, the issue is infact 4 years old. Balena now supports a ton of devices, so having info on specific PSU's for each board might not be a list that would be beneficial to maintain. We can close the issue cc @shaunmulligan if you have thoughts since you created the issue.

**Comment by lurch** [comment] 2020-12-29 02:20
> How about a small FAQ answer on the FAQ page about better reading voltage requirements to pick the right PSU for the board that customers might be using?

Just a quick comment to add that the current-requirements are just as important as the voltage-requirements. A PSU with too high voltage may damage the board, but a PSU with too low voltage will probably cause the board to fail to boot. Whereas if the PSU isn't capable of providing the maximum current that the board can demand (which is what I was referring to by "insufficient" in my previous comment) then the board may boot okay (giving the user the impression that everything is "okay"), but then later on (when a CPU-intensive task kicks in) the board may try to draw more current than the PSU is capable of, which then leads to the brown-out (i.e. the board unexpectedly resetting).

> Any useful advice other than what's already mentioned here under power - https://www.balena.io/docs/learn/welcome/production-plan/#hardware

That page says "the power supply is capable and actually providing the required power" - looks like that might be a typo for "the power supply is capable **of** actually providing the required power" ? :shrug:

**Comment by vipulgupta2048** [comment] 2021-01-04 18:08
Hey @lurch Thanks for the comments. Information like this is exactly what might help a new user or a customer running a fleet deploy with fewer issues. Would you like to take a shot at this and we can continue the discussion in the PR?

**Comment by lurch** [comment] 2021-01-05 03:03
I'm happy to provide helpful comments, but I don't have time to create PRs, sorry.

**Comment by vipulgupta2048** [comment] 2021-01-05 13:57
@lurch No apologies needed, we will take whatever help we can get :hatching_chick: Thanks for sticking around. I will put down your comments in a PR and put this 4-year-old issue to bed.

**Comment by lurch** [comment] 2021-01-05 14:06
It might also be worth noting that with the increased power-requirements of e.g. the Pi3 and the Pi4, trying to power them with a low-quality phone-charger might not even get them past the boot-stage; so this issue of low-current power supplies causing unexpected resets during high CPU-load _might_ be less prevalent than it was 5 years ago? :wink: :shrug:

**Closed** 2021-01-26 17:23 UTC
Labels: reference/hardware, scope/enhancement
