### ISSUE TITLE
Broken links on "Supported Architectures" page

### ISSUE THREAD

**Issue by builder555** [balena-io/docs#1971] opened 2021-07-07 15:55 UTC
[This page](https://www.balena.io/os/docs/supported-boards/) Contains a few links to the boards' websites that are throwing 404's:

https://forums.balena.io/c/balena-os
https://www.raspberrypi.org/products/model-a-plus/
https://www.raspberrypi.org/products/pi-zero/
https://boundarydevices.com/product/nitrogen6x-board-imx6-arm-cortex-a9-sbc/
https://www.solid-run.com/product-tag/hummingboard-base/
https://www.hardkernel.com/main/products/prdt_info.php?g_code=G141578608433
https://www.hardkernel.com/main/products/prdt_info.php?g_code=G143452239825
https://www.artik.io/modules/overview/artik-10/
https://www.artik.io/modules/overview/artik-5/

**Comment by klutchell** [comment] 2021-07-07 17:06
Thanks for raising this issue!

These links are hardcoded here (private URL): https://github.com/balena-io/resin-site

So they aren't currently scanned with link-checker. We will have to go through them manually and clean them up

**Comment by vipulgupta2048** [comment] 2021-07-12 11:10
Thanks for bringing this to our attention @builder555  

@klutchell This page might be worth autogenerating for a more resilient fix. The task involves fetching the resources from the /v6/device-type endpoint and creating a table out of the supported devices if this is the right use case for this. Check out this PR for reference: https://github.com/balena-io/docs/pull/1915 

Also, isn't the balenaOS site being generated from github.com/balena-os/balena-os
I found the page that @builder555 mentions here https://github.com/balena-os/balena-os/blob/4e3c4ac88c28ed2df9d8758909e7a497d93086f6/pages/docs/supportedboards.md, maybe it got changed

Lastly, if it's in the same org I usually transfer issues out to other repos instead of linking issues in GitHub. It helps to maintain ownership and original thread context. But, that's more of a personal preference thing.

**Comment by klutchell** [comment] 2021-07-12 12:28
Good call @vipulgupta2048 , I didn't notice the balena-os repo had the same links. I wonder which is correct?

I see @builder555 has already PRd and fixed the URLs on resin-site.

https://github.com/balena-io/resin-site/blob/a821a9ba89e28aac4233f56179eb301a91a45a72/src/data/os/docs/supported-boards.md

I would normally transfer the issue as well, but I didn't in this case as resin-site is private and I didn't want anyone watching this issue to lose context. If they were both public I would have moved it, yeah.

**Comment by klutchell** [comment] 2021-07-31 12:52
Confirmed that this page seems not to be used anymore, I wonder why that is? I think we are missing some context here.

https://github.com/balena-os/balena-os/blob/master/pages/docs/supportedboards.md

The changes made to resin-site are correctly reflected online now.

https://github.com/balena-io/resin-site/commit/dd3f24c5f26ccb783d5fce8b70abbf778e50705a

@thgreasi Do you have any context as to why the balena-os supported boards docs are in two repos?

**Comment by vipulgupta2048** [comment] 2021-08-02 19:13
I think @iamsolankiamit would know about this ^^

**Comment by iamsolankiamit** [comment] 2021-08-04 08:44
@klutchell @vipulgupta2048 That folder in balena-os seems to be the older one before we moved the docs to resin-site. So it is not being used now.

**Comment by vipulgupta2048** [comment] 2021-08-04 08:51
Thanks @iamsolankiamit for the assist, I will make a PR to nuke that folder to reduce further confusion. I was actually thinking to add a GitHub button if possible to redirect folks to the repository from where docs are being generated. But, since resin-site is private I don't think that's possible. A lot of people come looking to fix things on the balenaOS docs and hence the need for the button like "Improve the Docs" would help quite a bit.

**Comment by iamsolankiamit** [comment] 2021-08-04 08:59
@vipulgupta2048 there is a script in docs which pulls from the balena-os repo, need to check which files are being pulled. Yes `balena.io/os` and the docs you find there are being built from resin-site

**Comment by vipulgupta2048** [comment] 2021-08-04 10:13
If that's the case @iamsolankiamit shouldn't all PR's be going to balena-os repository instead assuming the resin-site changes won't be persistent and get overwritten on next pull. At least that's what happens in balenacloud docs here.

**Comment by vipulgupta2048** [comment] 2021-08-04 15:13
@iamsolankiamit https://github.com/balena-io/docs/blob/master/tools/fetch-external.sh here it is. So what you mean is, 
- leave only the files we are pulling into docs 
- Delete the files being overlapped by resin-site
- Call it a day?

Will go through the repo today and update the readme with this information for folks that come on this repo next.

**Comment by vipulgupta2048** [comment] 2021-08-05 11:18
From one issue by @builder555 we are now fully deprecating a repository 😂 
Talk about the impact 💣

**Comment by vipulgupta2048** [comment] 2021-08-05 11:20
Closing with https://github.com/balena-io/resin-site/pull/1306

**Closed by vipulgupta2048** 2021-08-05 11:20 UTC
